#!/bin/sh

# Generate a random API key
API_KEY=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 48 | head -n 1)
sed -i "s/\$API_KEY/$API_KEY/g" /etc/typesense/typesense-server.ini

systemctl enable typesense-server
systemctl daemon-reload
systemctl start typesense-server